# Generated by Django 4.2.5 on 2023-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="manual_address",
            field=models.BooleanField(default=False),
        ),
    ]
