# Generated by Django 4.2.5 on 2023-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0004_address_manual_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locality",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="locality",
            name="province",
            field=models.CharField(blank=True, max_length=165),
        ),
        migrations.AlterUniqueTogether(
            name="locality",
            unique_together={("name", "postal_code", "state", "province")},
        ),
    ]
